export const signInActionTypes = {
    REQUEST_ACTION: 'SIGN_IN_REQUEST_ACTION',
    SUCCESS_ACTION: 'SIGN_IN_SUCCESS_ACTION',
    FAILED_ACTION: 'SIGN_IN_FAILED_ACTION',
    SESSION_EXPIRED_ACTION: 'SESSION_EXPIRED_ACTION'
}

export const navigationActionTypes = {
    REFRESH_NAVIGATION: 'REFRESH_NAVIGATION'
}

export const findUserActionTypes = {
    REQUEST_ACTION: 'FIND_USER_REQUEST_ACTION',
    SUCCESS_ACTION: 'FIND_USER_SUCCESS_ACTION',
    FAILED_ACTION: 'FIND_USER_FAILED_ACTION'
}

export const simpleUpdateActionTypes = {
    REQUEST_ACTION: 'SIMPLE_UPDATE_REQUEST_ACTION',
    SUCCESS_ACTION: 'SIMPLE_UPDATE_SUCCESS_ACTION',
    FAILED_ACTION: 'SIMPLE_UPDATE_FAILED_ACTION'
}

export const createWorkPlaceActionTypes = {
    REQUEST_ACTION: 'CREATE_WORKPLACE_REQUEST_ACTION',
    SUCCESS_ACTION: 'CREATE_WORKPLACE_SUCCESS_ACTION',
    FAILED_ACTION: 'CREATE_WORKPLACE_FAILED_ACTION'
}

export const updateWorkPlaceActionTypes = {
    REQUEST_ACTION: 'UPDATE_WORKPLACE_REQUEST_ACTION',
    SUCCESS_ACTION: 'UPDATE_WORKPLACE_SUCCESS_ACTION',
    FAILED_ACTION: 'UPDATE_WORKPLACE_FAILED_ACTION'
}

export const searchWorkPlaceActionTypes = {
    REQUEST_ACTION: 'SEARCH_WORKPLACE_REQUEST_ACTION',
    SUCCESS_ACTION: 'SEARCH_WORKPLACE_SUCCESS_ACTION',
    FAILED_ACTION: 'SEARCH_WORKPLACE_FAILED_ACTION'
}

export const searchWorkPlaceByIdActionTypes = {
    REQUEST_ACTION: 'SEARCH_WORKPLACE_BY_ID_REQUEST_ACTION',
    SUCCESS_ACTION: 'SEARCH_WORKPLACE_BY_ID_SUCCESS_ACTION',
    FAILED_ACTION: 'SEARCH_WORKPLACE_BY_ID_FAILED_ACTION'
}

export const searchPlansActionTypes = {
    REQUEST_ACTION: 'SEARCH_PLANS_REQUEST_ACTION',
    SUCCESS_ACTION: 'SEARCH_PLANS_SUCCESS_ACTION',
    FAILED_ACTION: 'SEARCH_PLANS_FAILED_ACTION'
}

export const createOrUpdatePlanActionTypes = {
    REQUEST_ACTION: 'CREATE_OR_UPDATE_PLANS_REQUEST_ACTION',
    SUCCESS_ACTION: 'CREATE_OR_UPDATE_PLANS_SUCCESS_ACTION',
    FAILED_ACTION: 'CREATE_OR_UPDATE_PLANS_FAILED_ACTION'
}

export const deletePlanActionTypes = {
    REQUEST_ACTION: 'DELETE_PLAN_REQUEST_ACTION',
    SUCCESS_ACTION: 'DELETE_PLAN_SUCCESS_ACTION',
    FAILED_ACTION: 'DELETE_PLAN_FAILED_ACTION'
}

export const itemListActionTypes = {
    REQUEST_ACTION: 'ITEMS_BY_PLAN_REQUEST_ACTION',
    SUCCESS_ACTION: 'ITEMS_BY_PLAN_SUCCESS_ACTION',
    FAILED_ACTION: 'ITEMS_BY_PLAN_FAILED_ACTION'
}

export const itemCreateUpdateActionTypes = {
    REQUEST_ACTION: 'ITEM_CREATE_UPDATE_REQUEST_ACTION',
    SUCCESS_ACTION: 'ITEM_CREATE_UPDATE_SUCCESS_ACTION',
    FAILED_ACTION: 'ITEM_CREATE_UPDATE_FAILED_ACTION',
    CLEAR_ACTION: 'ITEM_CLEAR_ACTION'
}

export const deleteItemActionTypes = {
    REQUEST_ACTION: 'DELETE_ITEM_REQUEST_ACTION',
    SUCCESS_ACTION: 'DELETE_ITEM_SUCCESS_ACTION',
    FAILED_ACTION: 'DELETE_ITEM_FAILED_ACTION'
}

export const findAllBusinessTypesActionTypes = {
    REQUEST_ACTION: 'FIND_ALL_BUSINESS_TYPES_REQUEST_ACTION',
    SUCCESS_ACTION: 'FIND_ALL_BUSINESS_TYPES_SUCCESS_ACTION',
    FAILED_ACTION: 'FIND_ALL_BUSINESS_TYPES_FAILED_ACTION'
}

export const findAllCategoriesActionTypes = {
    REQUEST_ACTION: 'FIND_ALL_CATEGORIES_REQUEST_ACTION',
    SUCCESS_ACTION: 'FIND_ALL_CATEGORIES_SUCCESS_ACTION',
    FAILED_ACTION: 'FIND_ALL_CATEGORIES_FAILED_ACTION'
}

export const findAllOrdersActionTypes = {
    REQUEST_ACTION: 'ALL_ORDERS_REQUEST_ACTION',
    SUCCESS_ACTION: 'ALL_ORDERS_SUCCESS_ACTION',
    FAILED_ACTION: 'ALL_ORDERS_FAILED_ACTION'
}

export const createUpdateOrdersActionTypes = {
    REQUEST_ACTION: 'CREATE_UPDATE_ORDERS_REQUEST_ACTION',
    SUCCESS_ACTION: 'CREATE_UPDATE_ORDERS_SUCCESS_ACTION',
    FAILED_ACTION: 'CREATE_UPDATE_ORDERS_FAILED_ACTION'
}

export const deleteOrderActionTypes = {
    REQUEST_ACTION: 'DELETE_ORDER_REQUEST_ACTION',
    SUCCESS_ACTION: 'DELETE_ORDER_SUCCESS_ACTION',
    FAILED_ACTION: 'DELETE_ORDER_FAILED_ACTION'
}

export const updatePaymentStatusActionTypes = {
    REQUEST_ACTION: 'UPDATE_PAYMENT_STATUS_REQUEST_ACTION',
    SUCCESS_ACTION: 'UPDATE_PAYMENT_STATUS_SUCCESS_ACTION',
    FAILED_ACTION: 'UPDATE_PAYMENT_STATUS_FAILED_ACTION'
}

export const findAllOrderDetailsActionTypes = {
    REQUEST_ACTION: 'ALL_ORDER_DETAILS_REQUEST_ACTION',
    SUCCESS_ACTION: 'ALL_ORDER_DETAILS_SUCCESS_ACTION',
    FAILED_ACTION: 'ALL_ORDER_DETAILS_FAILED_ACTION',
    CLEAR_ACTION: 'CLEAR_ALL_ORDER_DETAILS_ACTION'
}

export const findPaymentHistoryActionTypes = {
    REQUEST_ACTION: 'GET_PAYMENT_HISTORY_REQUEST_ACTION',
    SUCCESS_ACTION: 'GET_PAYMENT_HISTORY_SUCCESS_ACTION',
    FAILED_ACTION: 'GET_PAYMENT_HISTORY_FAILED_ACTION'
}

export const addNewPaymentActionTypes = {
    REQUEST_ACTION: 'ADD_NEW_PAYMENT_REQUEST_ACTION',
    SUCCESS_ACTION: 'ADD_NEW_PAYMENT_SUCCESS_ACTION',
    FAILED_ACTION: 'ADD_NEW_PAYMENT_FAILED_ACTION'
}

export const deletePaymentActionTypes = {
    REQUEST_ACTION: 'DELETE_PAYMENT_REQUEST_ACTION',
    SUCCESS_ACTION: 'DELETE_PAYMENT_SUCCESS_ACTION',
    FAILED_ACTION: 'DELETE_PAYMENT_FAILED_ACTION'
}

export const shopCreateUpdateActionTypes = {
    REQUEST_ACTION: 'SHOP_CREATE_UPDATE_REQUEST_ACTION',
    SUCCESS_ACTION: 'SHOP_CREATE_UPDATE_SUCCESS_ACTION',
    FAILED_ACTION: 'SHOP_CREATE_UPDATE_FAILED_ACTION'
}

export const findAllShopsActionTypes = {
    REQUEST_ACTION: 'FIND_ALL_SHOPS_REQUEST_ACTION',
    SUCCESS_ACTION: 'FIND_ALL_SHOPS_SUCCESS_ACTION',
    FAILED_ACTION: 'FIND_ALL_SHOPS_FAILED_ACTION',
    RESET_SHOP_ACTION: 'RESET_ALL_SHOPS_ACTION'
}

export const deleteShopActionTypes = {
    REQUEST_ACTION: 'DELETE_SHOP_REQUEST_ACTION',
    SUCCESS_ACTION: 'DELETE_SHOP_SUCCESS_ACTION',
    FAILED_ACTION: 'DELETE_SHOP_FAILED_ACTION'
}

export const createUpdateUserActionTypes = {
    REQUEST_ACTION: 'CREATE_UPDATE_USER_REQUEST_ACTION',
    SUCCESS_ACTION: 'CREATE_UPDATE_USER_SUCCESS_ACTION',
    FAILED_ACTION: 'CREATE_UPDATE_USER_FAILED_ACTION'
}

export const deleteUserActionTypes = {
    REQUEST_ACTION: 'DELETE_USER_REQUEST_ACTION',
    SUCCESS_ACTION: 'DELETE_USER_SUCCESS_ACTION',
    FAILED_ACTION: 'DELETE_USER_FAILED_ACTION'
}

export const changePasswordActionTypes = {
    REQUEST_ACTION: 'CHANGE_PASSWORD_REQUEST_ACTION',
    SUCCESS_ACTION: 'CHANGE_PASSWORD_SUCCESS_ACTION',
    FAILED_ACTION: 'CHANGE_PASSWORD_FAILED_ACTION'
}

export const findAllUserActionTypes = {
    REQUEST_ACTION: 'FIND_ALL_USER_REQUEST_ACTION',
    SUCCESS_ACTION: 'FIND_ALL_USER_SUCCESS_ACTION',
    FAILED_ACTION: 'FIND_ALL_USER_FAILED_ACTION'
}

export const resetActionTypes = {
    WORKPLACE_RESET_ACTION: 'WORKPLACE_MESSAGE_RESET_ACTION',
    AUTH_RESET_ACTION: 'AUTH_MESSAGE_RESET_ACTION',
    PLAN_RESET_ACTION: 'PLAN_MESSAGE_RESET_ACTION',
    ITEM_RESET_ACTION: 'ITEM_MESSAGE_RESET_ACTION',
    ORDER_RESET_ACTION: 'ORDER_MESSAGE_RESET_ACTION',
    COMMON_RESET_ACTION: 'COMMON_MESSAGE_RESET_ACTION',
    SHOP_RESET_ACTION: 'SHOP_MESSAGE_RESET_ACTION',
    USER_RESET_ACTION: 'USER_MESSAGE_RESET_ACTION'
}

export const languageActionTypes = {
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE'
}
